inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 3.0.2
  NewCops: enable
  DisplayCopNames: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Naming/MethodParameterName:
  AllowedNames:
    - as

Metrics/AbcSize:
  Max: 21
  Exclude:

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 130

Metrics/BlockLength:
  Max: 120

SignalException:
  EnforcedStyle: semantic

Layout/EmptyLineAfterGuardClause:
  Enabled: false
